"""criar tabelas iniciais

Revision ID: 21d39b82bb94
Revises: 
Create Date: 2026-03-11 14:58:33.208646
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '21d39b82bb94'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('email_dono', sa.String(length=255), nullable=False),
    sa.Column('plano', sa.Enum('FREE', 'STARTER', 'PROFESSIONAL', 'ENTERPRISE', name='tenantplano'), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'SUSPENSO', 'TRIAL', 'CANCELADO', name='tenantstatus'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('indices_markup',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('percentual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indices_markup_tenant_id'), 'indices_markup', ['tenant_id'], unique=False)
    op.create_table('markups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('fator', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markups_tenant_id'), 'markups', ['tenant_id'], unique=False)
    op.create_table('nutricionistas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('crn', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutricionistas_tenant_id'), 'nutricionistas', ['tenant_id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('nutricionista_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nutricionista_id'], ['nutricionistas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_tenant_id'), 'clientes', ['tenant_id'], unique=False)
    op.create_table('ingredientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('unidade_medida', sa.Enum('KG', 'G', 'ML', 'L', 'UNIDADE', name='unidademedida'), nullable=False),
    sa.Column('custo_unitario', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('markup_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['markup_id'], ['markups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredientes_tenant_id'), 'ingredientes', ['tenant_id'], unique=False)
    op.create_table('markup_indices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('markup_id', sa.UUID(), nullable=False),
    sa.Column('indice_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['indice_id'], ['indices_markup.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['markup_id'], ['markups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markup_indices_tenant_id'), 'markup_indices', ['tenant_id'], unique=False)
    op.create_table('orcamentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('RASCUNHO', 'ENVIADO', 'APROVADO', 'REPROVADO', 'CANCELADO', name='statusorcamento'), nullable=False),
    sa.Column('markup_id', sa.UUID(), nullable=True),
    sa.Column('custo_ingredientes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('custo_embalagem', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('taxa_entrega', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('custo_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_final', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('validade_dias', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['markup_id'], ['markups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orcamentos_numero'), 'orcamentos', ['numero'], unique=False)
    op.create_index(op.f('ix_orcamentos_tenant_id'), 'orcamentos', ['tenant_id'], unique=False)
    op.create_table('orcamento_itens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('orcamento_id', sa.UUID(), nullable=False),
    sa.Column('ingrediente_id', sa.UUID(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unidade_medida', sa.Enum('KG', 'G', 'ML', 'L', 'UNIDADE', name='unidademedida'), nullable=False),
    sa.Column('custo_unitario_snapshot', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('markup_fator_snapshot', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('custo_total_item', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_item_com_markup', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orcamento_itens_tenant_id'), 'orcamento_itens', ['tenant_id'], unique=False)
    op.create_table('pedidos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('orcamento_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('AGUARDANDO_PRODUCAO', 'EM_PRODUCAO', 'PRONTO', 'ENTREGUE', 'CANCELADO', name='statuspedido'), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('taxa_entrega', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('custo_embalagem', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_entrega_prevista', sa.DateTime(), nullable=True),
    sa.Column('data_entrega_realizada', sa.DateTime(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orcamento_id')
    )
    op.create_index(op.f('ix_pedidos_numero'), 'pedidos', ['numero'], unique=False)
    op.create_index(op.f('ix_pedidos_tenant_id'), 'pedidos', ['tenant_id'], unique=False)
    op.create_table('pedido_itens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pedido_id', sa.UUID(), nullable=False),
    sa.Column('ingrediente_id', sa.UUID(), nullable=False),
    sa.Column('nome_ingrediente_snapshot', sa.String(length=255), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unidade_medida', sa.Enum('KG', 'G', 'ML', 'L', 'UNIDADE', name='unidademedida'), nullable=False),
    sa.Column('custo_unitario_snapshot', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('custo_total_item', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_itens_tenant_id'), 'pedido_itens', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedido_itens_tenant_id'), table_name='pedido_itens')
    op.drop_table('pedido_itens')
    op.drop_index(op.f('ix_pedidos_tenant_id'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_numero'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_orcamento_itens_tenant_id'), table_name='orcamento_itens')
    op.drop_table('orcamento_itens')
    op.drop_index(op.f('ix_orcamentos_tenant_id'), table_name='orcamentos')
    op.drop_index(op.f('ix_orcamentos_numero'), table_name='orcamentos')
    op.drop_table('orcamentos')
    op.drop_index(op.f('ix_markup_indices_tenant_id'), table_name='markup_indices')
    op.drop_table('markup_indices')
    op.drop_index(op.f('ix_ingredientes_tenant_id'), table_name='ingredientes')
    op.drop_table('ingredientes')
    op.drop_index(op.f('ix_clientes_tenant_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_nutricionistas_tenant_id'), table_name='nutricionistas')
    op.drop_table('nutricionistas')
    op.drop_index(op.f('ix_markups_tenant_id'), table_name='markups')
    op.drop_table('markups')
    op.drop_index(op.f('ix_indices_markup_tenant_id'), table_name='indices_markup')
    op.drop_table('indices_markup')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
