"""adicionar markup_padrao em tenant e cliente

Revision ID: 341fedffde18
Revises: dfbf002645a9
Create Date: 2026-03-17 15:47:57.383141
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '341fedffde18'
down_revision: Union[str, None] = 'dfbf002645a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('markup_id_padrao', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'clientes', 'markups', ['markup_id_padrao'], ['id'], ondelete='SET NULL')
    op.add_column('tenants', sa.Column('markup_id_padrao', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tenants', 'markups', ['markup_id_padrao'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_column('tenants', 'markup_id_padrao')
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.drop_column('clientes', 'markup_id_padrao')
    # ### end Alembic commands ###
