"""renomear constraint unique orcamento_id

Revision ID: dfbf002645a9
Revises: 21d39b82bb94
Create Date: 2026-03-12 07:14:30.495140
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'dfbf002645a9'
down_revision: Union[str, None] = '21d39b82bb94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pedidos_orcamento_id_key'), 'pedidos', type_='unique')
    op.create_unique_constraint('uq_pedido_orcamento', 'pedidos', ['orcamento_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_pedido_orcamento', 'pedidos', type_='unique')
    op.create_unique_constraint(op.f('pedidos_orcamento_id_key'), 'pedidos', ['orcamento_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
