sonar.projectKey=benedere-backend
sonar.projectName=Benedere Backend
sonar.sources=app
sonar.tests=tests
sonar.language=py
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/__pycache__/**,**/migrations/**,**/.venv/**
